Process Process-8:
Traceback (most recent call last):
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "../bin/ka_ks_pipe.py", line 178, in align_pair_codeml
    ds = la[13]
IndexError: list index out of range
Process Process-36:
Traceback (most recent call last):
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "../bin/ka_ks_pipe.py", line 178, in align_pair_codeml
    ds = la[13]
IndexError: list index out of range
Process Process-73:
Traceback (most recent call last):
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "../bin/ka_ks_pipe.py", line 178, in align_pair_codeml
    ds = la[13]
IndexError: list index out of range
Process Process-72:
Traceback (most recent call last):
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "../bin/ka_ks_pipe.py", line 178, in align_pair_codeml
    ds = la[13]
IndexError: list index out of range
Process Process-35:
Traceback (most recent call last):
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "../bin/ka_ks_pipe.py", line 178, in align_pair_codeml
    ds = la[13]
IndexError: list index out of range
Process Process-80:
Traceback (most recent call last):
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "../bin/ka_ks_pipe.py", line 178, in align_pair_codeml
    ds = la[13]
IndexError: list index out of range
Traceback (most recent call last):
  File "../bin/ka_ks_pipe.py", line 270, in <module>
    lol = q.get()
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/cluster/home/ayocca/miniconda3/envs/ka_ks_pipe/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
